language: node_js
node_js:
  - "5"

before_install:
  - 'git checkout -B $TRAVIS_BRANCH' # Reconcile detached HEAD
  - 'if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi'

script:
  - 'npm install --ignore-scripts'
  - 'npm run build'
  - 'npm run test'

after_success:
  - sh -x ./scripts/publish.sh

notifications:
  email:
    - patternfly-build@redhat.com